version: '3.5'

services:
  stem24-backend:
    image: stem24-backend:dev
    container_name: stem24-backend
    build: ./
    #restart: always
    ports:
      - 7080:8080
    volumes:
      - ./:/app
      - ./docker/wait-for.sh:/wait-for.sh
    networks:
      - live
    entrypoint: bash -c '/wait-for.sh live-database:5432 -t 60 -- go run cmd/stem24-backend/main.go'

networks:
  live:
    name: 'live'
